# Banking Loans Data Analysis

### Project Overview

This project focuses on analyzing a banking loans dataset to assess data quality, perform data cleaning, explore
patterns, and answer relevant business questions using Python and its data analysis libraries.

The project follows the data analysis workflow:
Data Understanding, Data Exploration, Data Cleaning, Feature Engineering (if required), and Data Analysis.


## Dataset Understanding

The Banking Loans Dataset contains information about loan accounts, customer characteristics, loan terms, credit risk indicators, and repayment-related metrics.

The dataset is used to assess data quality, perform data cleaning, explore patterns, and answer business-related questions using data analysis and visualization.

## Dataset:

| Column                    | Description                                                      |
| ------------------------- | ---------------------------------------------------------------- |
| `record_id`               | Unique identifier for each record in the dataset                 |
| `loan_id`                 | Identifier of the loan account                                   |
| `customer_age`            | Age of the customer in years                                     |
| `city`                    | City where the customer or loan account is located               |
| `branch`                  | Bank branch associated with the loan account                     |
| `employment_status`       | Employment status of the customer                                |
| `annual_income_egp`       | Customer's annual income in Egyptian Pounds (EGP)                |
| `loan_type`               | Type of loan associated with the account                         |
| `loan_purpose`            | Purpose for which the loan was taken                             |
| `loan_amount_egp`         | Original loan amount in Egyptian Pounds (EGP)                    |
| `interest_rate_pct`       | Interest rate applied to the loan, expressed as a percentage     |
| `term_months`             | Loan repayment term in months                                    |
| `credit_score`            | Customer's credit score used as an indicator of creditworthiness |
| `debt_to_income_pct`      | Customer's debt-to-income ratio, expressed as a percentage       |
| `risk_grade`              | Risk classification assigned to the loan or customer             |
| `origination_date`        | Date on which the loan was originated                            |
| `application_channel`     | Channel through which the loan application was submitted         |
| `loan_status`             | Current status of the loan account                               |
| `monthly_installment_egp` | Monthly loan installment amount in Egyptian Pounds (EGP)         |
| `remaining_balance_egp`   | Outstanding loan balance remaining in Egyptian Pounds (EGP)      |

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

## Load the Dataset

The Banking Loans Dataset will be loaded into a Pandas DataFrame to prepare it for data inspection, cleaning, analysis, and visualization.

In [5]:
df = pd.read_csv('banking_loans_mid_project_FINAL.csv')
df.head()

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
0,1,LN109160,32.0,Aswan,Mansoura Branch,Salaried,34141.0,Mortgage,Education,1155415,10.64,36,555.0,95.00,E,1/19/2025,Relationship Manager,Defaulted,37630.14,431740.31
1,2,LN101801,66.0,Aswan,Aswan Branch,Salaried,34631.0,Education Loan,Medical,22238,7.22,36,514.0,57.15,E,10/20/2023,Branch,Active,688.87,17359.26
2,3,LN102666,29.0,Port Said,Mansoura Branch,Self-Employed,49700.0,Education Loan,Medical,236672,11.75,120,725.0,25.27,B,11/26/2019,Online,Active,3361.43,113965.42
3,4,LN102617,43.0,Giza,Giza Main,Salaried,14385.0,Business Loan,Education,183922,16.34,60,629.0,82.46,D,7/12/2021,Branch,Active,4505.91,108513.48
4,5,LN110048,61.0,Ismailia,Cairo Main,Business Owner,19550.0,Mortgage,Medical,182772,6.58,72,756.0,55.46,A,8/25/2023,Mobile App,Closed,3079.35,0.00

## Quality Assessment and Statistical Summary (Categorical/Numerical)

In [8]:
df.shape

(12035, 20)

In [9]:
df.dtypes

record_id                    int64
loan_id                     object
customer_age               float64
city                        object
branch                      object
employment_status           object
annual_income_egp          float64
loan_type                   object
loan_purpose                object
loan_amount_egp              int64
interest_rate_pct          float64
term_months                  int64
credit_score               float64
debt_to_income_pct         float64
risk_grade                  object
origination_date            object
application_channel         object
loan_status                 object
monthly_installment_egp    float64
remaining_balance_egp      float64
dtype: object

In [11]:
df.isnull().sum()

record_id                    0
loan_id                      0
customer_age                 6
city                       100
branch                       0
employment_status          100
annual_income_egp          100
loan_type                    0
loan_purpose               100
loan_amount_egp              0
interest_rate_pct          100
term_months                  0
credit_score               100
debt_to_income_pct           0
risk_grade                   0
origination_date             0
application_channel          0
loan_status                  0
monthly_installment_egp      0
remaining_balance_egp        0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe()

,record_id,customer_age,annual_income_egp,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,monthly_installment_egp,remaining_balance_egp
count,12035.000000,12029.000000,11935.000000,1.203500e+04,11935.000000,12035.000000,11935.000000,12035.000000,12035.000000,1.203500e+04
mean,6018.000000,43.986200,42460.329032,3.709273e+05,13.021895,81.387619,675.697277,54.353267,10255.659091,1.752317e+05
std,3474.349579,13.471384,25135.185995,4.951326e+05,3.732852,61.460207,73.961150,24.546015,18251.612672,2.956804e+05
min,1.000000,18.000000,4199.000000,5.000000e+03,0.000000,12.000000,363.000000,5.520000,70.630000,0.000000e+00
25%,3009.500000,32.000000,25238.500000,8.378200e+04,9.830000,36.000000,625.000000,34.470000,1878.890000,1.917110e+04
50%,6018.000000,44.000000,36566.000000,1.884660e+05,13.060000,60.000000,677.000000,54.310000,4464.520000,6.868319e+04
75%,9026.500000,56.000000,52919.500000,4.542800e+05,16.230000,120.000000,726.000000,73.105000,11295.535000,2.000946e+05
max,12035.000000,67.000000,250000.000000,5.000000e+06,19.500000,240.000000,850.000000,95.000000,446867.930000,4.024504e+06

In [14]:
df.nunique()

record_id                  12035
loan_id                    11965
customer_age                  48
city                          22
branch                         6
employment_status              5
annual_income_egp          10793
loan_type                      6
loan_purpose                   7
loan_amount_egp            11848
interest_rate_pct           1302
term_months                   10
credit_score                 401
debt_to_income_pct          6013
risk_grade                     5
origination_date            2532
application_channel            4
loan_status                   14
monthly_installment_egp    11913
remaining_balance_egp       9992
dtype: int64

In [15]:
df["loan_id"].duplicated().sum()

np.int64(70)

In [16]:
df.loc[df["loan_id"].duplicated(keep=False), "loan_id"].value_counts()

loan_id
LN104160    2
LN111813    2
LN107200    2
LN106048    2
LN110932    2
           ..
LN108619    2
LN100472    2
LN105059    2
LN100012    2
LN109130    2
Name: count, Length: 70, dtype: int64

In [18]:
duplicate_loans = df[df["loan_id"].duplicated(keep=False)].sort_values("loan_id")
duplicate_loans

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
10394,10395,LN100012,56.0,Alexandria,Aswan Branch,Retired,13275.0,Education Loan,Education,77496,7.95,60,734.0,31.54,B,9/5/2021,Branch,Closed,1569.49,0.00
10429,10430,LN100012,56.0,Alexandria,Aswan Branch,Retired,13275.0,Education Loan,Education,77496,7.95,60,734.0,31.54,B,9/5/2021,Branch,Closed,1569.49,0.00
11090,11091,LN100191,62.0,Aswan,Cairo Main,Unemployed,43729.0,Personal Loan,Business Expansion,80499,7.26,240,624.0,57.31,D,3/16/2025,Mobile App,Restructured,636.74,34658.92
7162,7163,LN100191,62.0,Aswan,Cairo Main,Unemployed,43729.0,Personal Loan,Business Expansion,80499,7.26,240,624.0,57.31,D,3/16/2025,Mobile App,Restructured,636.74,34658.92
6564,6565,LN100247,53.0,Aswan,Giza Main,Self-Employed,30954.0,Business Loan,Education,222822,16.26,36,723.0,48.24,B,5/19/2025,Online,Closed,7862.38,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6871,6872,LN111237,38.0,Giza,Alexandria Main,Salaried,15544.0,Auto Loan,Home Purchase,112095,12.61,72,796.0,76.27,A,3/16/2024,Mobile App,Defaulted,2227.19,60484.51
9916,9917,LN111279,46.0,Cairo,Tanta Branch,Salaried,48514.0,Home Improvement,Medical,369667,14.09,180,675.0,38.02,C,8/15/2020,Branch,Closed,4945.38,0.00
9185,9186,LN111279,46.0,Cairo,Tanta Branch,Salaried,48514.0,Home Improvement,Medical,369667,14.09,180,675.0,38.02,C,8/15/2020,Branch,Closed,4945.38,0.00
81,82,LN111813,43.0,Cairo,Aswan Branch,Salaried,32577.0,Home Improvement,Personal Expenses,282666,19.27,60,638.0,63.68,D,3/18/2024,Relationship Manager,Defaulted,7374.58,170429.63
4186,4187,LN111813,43.0,Cairo,Aswan Branch,Salaried,32577.0,Home Improvement,Personal Expenses,282666,19.27,60,638.0,63.68,D,3/18/2024,Relationship Manager,Defaulted,7374.58,170429.63

In [19]:
duplicate_loans.drop(columns=["record_id", "loan_id"]).duplicated().sum()

np.int64(64)

In [23]:
duplicate_loans.groupby("loan_id").nunique().loc[lambda x: x.max(axis=1) > 1]

,record_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
loan_id,,,,,,,,,,,,,,,,,,,
LN100012,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN100191,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN100247,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN100472,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN100694,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LN111139,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN111148,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN111237,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN111279,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN111813,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [22]:
duplicate_comparison = duplicate_loans.drop(columns=["record_id"]).groupby("loan_id").nunique()

duplicate_comparison[duplicate_comparison.max(axis=1) > 1]

Empty DataFrame
Columns: [customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [24]:
df["loan_status"].value_counts()

loan_status
Active           5986
Defaulted        2244
Closed           1983
Restructured     1184
Written Off       613
active              7
 Active             4
 Defaulted          4
restructured        3
 Written Off        2
closed              2
written off         1
defaulted           1
 Restructured       1
Name: count, dtype: int64

In [25]:
df["employment_status"].value_counts()

employment_status
Salaried          6312
Self-Employed     2261
Business Owner    1454
Retired           1191
Unemployed         717
Name: count, dtype: int64

In [26]:
df["city"].value_counts()

city
Mansoura       1690
Giza           1483
Cairo          1482
Aswan          1470
Alexandria     1468
Ismailia       1441
Tanta          1440
Port Said      1435
aswan             4
alexandria        3
 Ismailia         3
mansoura          2
port said         2
 Alexandria       2
 Tanta            2
tanta             2
ismailia          1
 Aswan            1
 Cairo            1
giza              1
cairo             1
 Mansoura         1
Name: count, dtype: int64

In [27]:
df["branch"].value_counts()

branch
Aswan Branch       2075
Giza Main          2074
Tanta Branch       2022
Mansoura Branch    1976
Alexandria Main    1961
Cairo Main         1927
Name: count, dtype: int64

In [28]:
df["loan_type"].value_counts()

loan_type
Personal Loan       3035
Business Loan       2561
Mortgage            2137
Auto Loan           1853
Home Improvement    1284
Education Loan      1165
Name: count, dtype: int64

In [29]:
df["loan_purpose"].value_counts()

loan_purpose
Medical               1895
Personal Expenses     1708
Education             1697
Business Expansion    1691
Home Purchase         1676
Vehicle Purchase      1654
Debt Consolidation    1614
Name: count, dtype: int64

In [30]:
df["risk_grade"].value_counts()

risk_grade
C    3108
B    2587
D    2517
A    1965
E    1858
Name: count, dtype: int64

In [31]:
df["application_channel"].value_counts()

application_channel
Branch                  4705
Online                  2975
Mobile App              2515
Relationship Manager    1840
Name: count, dtype: int64

In [32]:
df["loan_status"].unique()

array(['Defaulted', 'Active', 'Closed', 'Written Off', 'Restructured',
       'written off', 'active', 'defaulted', ' Defaulted', 'restructured',
       ' Active', 'closed', ' Restructured', ' Written Off'], dtype=object)

In [33]:
df["origination_date"].unique()[:20]

array(['1/19/2025', '10/20/2023', '11/26/2019', '7/12/2021', '8/25/2023',
       '4/5/2024', '7/30/2024', '9/27/2025', '1/22/2025', '10/9/2023',
       '12/10/2019', '1/22/2019', '4/3/2023', '6/29/2024', '8/23/2022',
       '4/16/2023', '1/12/2022', '7/13/2024', '12/9/2024', '1/9/2024'],
      dtype=object)

In [34]:
pd.to_datetime(df["origination_date"], errors="coerce").isna().sum()

np.int64(0)

In [35]:
df["interest_rate_pct"].value_counts().sort_index().head(15)

interest_rate_pct
0.00     1
6.50     4
6.51    16
6.52    11
6.53    10
6.54    12
6.55    10
6.56     6
6.57     9
6.58     6
6.59     8
6.60    12
6.61     8
6.62     7
6.63    11
Name: count, dtype: int64

In [36]:
df[df["interest_rate_pct"] == 0]

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
2677,2678,LN111911,22.0,Port Said,Mansoura Branch,Salaried,13833.0,Mortgage,Medical,369282,0.0,72,636.0,95.0,D,6/12/2023,Mobile App,Restructured,7281.13,309358.76

In [37]:
df[(df["credit_score"] < 300) | (df["credit_score"] > 850)]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [38]:
df[(df["customer_age"] < 18) | (df["customer_age"] > 100)]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [39]:
df[(df["debt_to_income_pct"] < 0) | (df["debt_to_income_pct"] > 100)]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [40]:
df[df["annual_income_egp"] <= 0]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [41]:
df[df["loan_amount_egp"] <= 0]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [43]:
df.groupby("loan_status")["remaining_balance_egp"].agg(["count", "min", "max", "mean"]).round(2)

               count        min         max       mean
loan_status
 Active            4   22456.55   379113.46  175148.56
 Defaulted         4   18514.49   286887.22  126973.66
 Restructured      1  520767.93   520767.93  520767.93
 Written Off       2    9446.70    29978.25   19712.47
Active          5986    1244.74  4024504.19  179446.01
Closed          1983       0.00        0.00       0.00
Defaulted       2244    1396.36  4012521.11  256818.31
Restructured    1184    2416.09  2769925.28  256079.46
Written Off      613    1866.21  3271091.40  248418.02
active             7   16486.82   381642.74  102026.18
closed             2       0.00        0.00       0.00
defaulted          1  334007.95   334007.95  334007.95
restructured       3    5240.18    26659.37   16850.86
written off        1  103600.24   103600.24  103600.24

In [44]:
df[df["monthly_installment_egp"] <= 0]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

## Initial Data Quality Assessment

The dataset was reviewed for missing values, duplicate records, duplicate loan IDs, categorical inconsistencies, data types, and basic numerical validity.

The main data quality issues identified were:

- Missing values in 7 columns.
- Duplicate `loan_id` values.
- Inconsistent formatting in the `city` column.
- Inconsistent formatting in the `loan_status` column.
- `origination_date` stored as an object instead of datetime.
- One potential anomaly in `interest_rate_pct` with a value of 0.00%.

No full-row duplicates were found, and no invalid ranges were identified for the main numerical fields checked.

The identified issues will be addressed during the data cleaning stage.